export const ADD_LIST = "ADD_LIST";
export const REMOVE_LIST = "REMOVE_LIST";

export const ADD_HERO = "ADD_HERO";
export const REMOVE_HERO = "REMOVE_HERO";

export const ADD_ATTRIBUTE_FILTER = "ADD_ATTRIBUTE_FILTER";
export const REMOVE_ATTRIBUTE_FILTER = "REMOVE_ATTRIBUTE_FILTER";

export const UPDATE_NAME_FILTER = "UPDATE_NAME_FILTER";

export const ADD_ATTACKTYPE_FILTER = "ADD_ATTACKTYPE_FILTER";
export const REMOVE_ATTACKTYPE_FILTER = "REMOVE_ATTACKTYPE_FILTER";