export const HERO_LIST = [
  { id: "abaddon", name: "Abaddon", primary: "strength", attackType: "MELEE" },
  { id: "abyssal_underlord", name: "Underlord", primary: "strength", attackType: "MELEE" },
  { id: "alchemist", name: "Alchemist", primary: "strength", attackType: "MELEE" },
  { id: "ancient_apparition", name: "Ancient Apparition", primary: "intelligence", attackType: "RANGED" },
  { id: "antimage", name: "Anti-Mage", primary: "agility", attackType: "MELEE" },
  { id: "arc_warden", name: "Arc Warden", primary: "agility", attackType: "RANGED" },
  { id: "axe", name: "Axe", primary: "strength", attackType: "MELEE" },
  { id: "bane", name: "Bane", primary: "intelligence", attackType: "RANGED" },
  { id: "batrider", name: "Batrider", primary: "intelligence", attackType: "RANGED" },
  { id: "beastmaster", name: "Beastmaster", primary: "strength", attackType: "MELEE" },
  { id: "bloodseeker", name: "Bloodseeker", primary: "agility", attackType: "MELEE" },
  { id: "bounty_hunter", name: "Bounty Hunter", primary: "agility", attackType: "MELEE" },
  { id: "brewmaster", name: "Brewmaster", primary: "strength", attackType: "MELEE" },
  { id: "bristleback", name: "Bristleback", primary: "strength", attackType: "MELEE" },
  { id: "broodmother", name: "Broodmother", primary: "agility", attackType: "MELEE" },
  { id: "centaur", name: "Centaur Warrunner", primary: "strength", attackType: "MELEE" },
  { id: "chaos_knight", name: "Chaos Knight", primary: "strength", attackType: "MELEE" },
  { id: "chen", name: "Chen", primary: "intelligence", attackType: "RANGED" },
  { id: "clinkz", name: "Clinkz", primary: "agility", attackType: "RANGED" },
  { id: "crystal_maiden", name: "Crystal Maiden", primary: "intelligence", attackType: "RANGED" },
  { id: "dark_seer", name: "Dark Seer", primary: "intelligence", attackType: "MELEE" },
  { id: "dark_willow", name: "Dark Willow", primary: "intelligence", attackType: "RANGED" },
  { id: "dazzle", name: "Dazzle", primary: "intelligence", attackType: "RANGED" },
  { id: "death_prophet", name: "Death Prophet", primary: "intelligence", attackType: "RANGED" },
  { id: "disruptor", name: "Disruptor", primary: "intelligence", attackType: "RANGED" },
  { id: "doom_bringer", name: "Doom", primary: "strength", attackType: "MELEE" },
  { id: "dragon_knight", name: "Dragon Knight", primary: "strength", attackType: "MELEE" },
  { id: "drow_ranger", name: "Drow Ranger", primary: "agility", attackType: "RANGED" },
  { id: "earthshaker", name: "Earth Spirit", primary: "strength", attackType: "MELEE" },
  { id: "earth_spirit", name: "Earthshaker", primary: "strength", attackType: "MELEE" },
  { id: "elder_titan", name: "Elder Titan", primary: "strength", attackType: "MELEE" },
  { id: "ember_spirit", name: "Ember Spirit", primary: "agility", attackType: "MELEE" },
  { id: "enchantress", name: "Enchantress", primary: "intelligence", attackType: "RANGED" },
  { id: "enigma", name: "Enigma", primary: "intelligence", attackType: "RANGED" },
  { id: "faceless_void", name: "Faceless Void", primary: "agility", attackType: "MELEE" },
  { id: "furion", name: "Nature's Prophet", primary: "intelligence", attackType: "RANGED" },
  { id: "gyrocopter", name: "Gyrocopter", primary: "agility", attackType: "RANGED" },
  { id: "huskar", name: "Huskar", primary: "strength", attackType: "RANGED" },
  { id: "invoker", name: "Invoker", primary: "intelligence", attackType: "RANGED" },
  { id: "jakiro", name: "Jakiro", primary: "intelligence", attackType: "RANGED" },
  { id: "juggernaut", name: "Juggernaut", primary: "agility", attackType: "MELEE" },
  { id: "keeper_of_the_light", name: "Keeper of the Light", primary: "intelligence", attackType: "RANGED" },
  { id: "kunkka", name: "Kunkka", primary: "strength", attackType: "MELEE" },
  { id: "legion_commander", name: "Legion Commander", primary: "strength", attackType: "MELEE" },
  { id: "leshrac", name: "Leshrac", primary: "intelligence", attackType: "RANGED" },
  { id: "lich", name: "Lich", primary: "intelligence", attackType: "RANGED" },
  { id: "life_stealer", name: "Lifestealer", primary: "strength", attackType: "MELEE" },
  { id: "lina", name: "Lina", primary: "intelligence", attackType: "RANGED" },
  { id: "lion", name: "Lion", primary: "intelligence", attackType: "RANGED" },
  { id: "lone_druid", name: "Lone Druid", primary: "agility", attackType: "RANGED" },
  { id: "luna", name: "Luna", primary: "agility", attackType: "RANGED" },
  { id: "lycan", name: "Lycan", primary: "strength", attackType: "MELEE" },
  { id: "magnataur", name: "Magnus", primary: "strength", attackType: "MELEE" },
  { id: "medusa", name: "Medusa", primary: "agility", attackType: "RANGED" },
  { id: "meepo", name: "Meepo", primary: "agility", attackType: "MELEE" },
  { id: "mirana", name: "Mirana", primary: "agility", attackType: "RANGED" },
  { id: "monkey_king", name: "Monkey King", primary: "agility", attackType: "MELEE" },
  { id: "morphling", name: "Morphling", primary: "agility", attackType: "RANGED" },
  { id: "naga_siren", name: "Naga Siren", primary: "agility", attackType: "MELEE" },
  { id: "necrolyte", name: "Necrophos", primary: "intelligence", attackType: "RANGED" },
  { id: "nevermore", name: "Shadow Fiend", primary: "agility", attackType: "RANGED" },
  { id: "night_stalker", name: "Night Stalker", primary: "strength", attackType: "MELEE" },
  { id: "nyx_assassin", name: "Nyx Assassin", primary: "agility", attackType: "MELEE" },
  { id: "obsidian_destroyer", name: "Outworld Devourer", primary: "intelligence", attackType: "RANGED" },
  { id: "ogre_magi", name: "Ogre Magi", primary: "intelligence", attackType: "MELEE" },
  { id: "omniknight", name: "Omniknight", primary: "strength", attackType: "MELEE" },
  { id: "oracle", name: "Oracle", primary: "intelligence", attackType: "RANGED" },
  { id: "pangolier", name: "Pangolier", primary: "agility", attackType: "MELEE" },
  { id: "phantom_assassin", name: "Phantom Assassin", primary: "agility", attackType: "MELEE" },
  { id: "phantom_lancer", name: "Phantom Lancer", primary: "agility", attackType: "MELEE" },
  { id: "phoenix", name: "Phoenix", primary: "strength", attackType: "RANGED" },
  { id: "puck", name: "Puck", primary: "intelligence", attackType: "RANGED" },
  { id: "pudge", name: "Pudge", primary: "strength", attackType: "MELEE" },
  { id: "pugna", name: "Pugna", primary: "intelligence", attackType: "RANGED" },
  { id: "queenofpain", name: "Queen of Pain", primary: "intelligence", attackType: "RANGED" },
  { id: "rattletrap", name: "Clockwerk", primary: "strength", attackType: "MELEE" },
  { id: "razor", name: "Razor", primary: "agility", attackType: "RANGED" },
  { id: "riki", name: "Riki", primary: "agility", attackType: "MELEE" },
  { id: "rubick", name: "Rubick", primary: "intelligence", attackType: "RANGED" },
  { id: "sand_king", name: "Sand King", primary: "strength", attackType: "MELEE" },
  { id: "shadow_demon", name: "Shadow Demon", primary: "intelligence", attackType: "RANGED" },
  { id: "shadow_shaman", name: "Shadow Shaman", primary: "intelligence", attackType: "RANGED" },
  { id: "shredder", name: "Timbersaw", primary: "strength", attackType: "MELEE" },
  { id: "silencer", name: "Silencer", primary: "intelligence", attackType: "RANGED" },
  { id: "skeleton_king", name: "Wraith King", primary: "strength", attackType: "MELEE" },
  { id: "skywrath_mage", name: "Skywrath Mage", primary: "intelligence", attackType: "RANGED" },
  { id: "slardar", name: "Slardar", primary: "strength", attackType: "MELEE" },
  { id: "slark", name: "Slark", primary: "agility", attackType: "MELEE" },
  { id: "sniper", name: "Sniper", primary: "agility", attackType: "RANGED" },
  { id: "spectre", name: "Spectre", primary: "agility", attackType: "MELEE" },
  { id: "spirit_breaker", name: "Spirit Breaker", primary: "strength", attackType: "MELEE" },
  { id: "storm_spirit", name: "Storm Spirit", primary: "intelligence", attackType: "RANGED" },
  { id: "sven", name: "Sven", primary: "strength", attackType: "MELEE" },
  { id: "techies", name: "Techies", primary: "intelligence", attackType: "RANGED" },
  { id: "templar_assassin", name: "Templar Assassin", primary: "agility", attackType: "RANGED" },
  { id: "terrorblade", name: "Terrorblade", primary: "agility", attackType: "MELEE" },
  { id: "tidehunter", name: "Tidehunter", primary: "strength", attackType: "MELEE" },
  { id: "tinker", name: "Tinker", primary: "intelligence", attackType: "RANGED" },
  { id: "tiny", name: "Tiny", primary: "strength", attackType: "MELEE" },
  { id: "treant", name: "Treant Protector", primary: "strength", attackType: "MELEE" },
  { id: "troll_warlord", name: "Troll Warlord", primary: "agility", attackType: "RANGED" },
  { id: "tusk", name: "Tusk", primary: "strength", attackType: "MELEE" },
  { id: "undying", name: "Undying", primary: "strength", attackType: "MELEE" },
  { id: "ursa", name: "Ursa", primary: "agility", attackType: "MELEE" },
  { id: "vengefulspirit", name: "Vengeful Spirit", primary: "agility", attackType: "RANGED" },
  { id: "venomancer", name: "Venomancer", primary: "agility", attackType: "RANGED" },
  { id: "viper", name: "Viper", primary: "agility", attackType: "RANGED" },
  { id: "visage", name: "Visage", primary: "intelligence", attackType: "RANGED" },
  { id: "warlock", name: "Warlock", primary: "intelligence", attackType: "RANGED" },
  { id: "weaver", name: "Weaver", primary: "agility", attackType: "RANGED" },
  { id: "windrunner", name: "Windranger", primary: "intelligence", attackType: "RANGED" },
  { id: "winter_wyvern", name: "Winter Wyvern", primary: "intelligence", attackType: "RANGED" },
  { id: "wisp", name: "Io", primary: "strength", attackType: "RANGED" },
  { id: "witch_doctor", name: "Witch Doctor", primary: "intelligence", attackType: "RANGED" },
  { id: "zuus", name: "Zeus", primary: "intelligence", attackType: "RANGED" }
];

export const ATTRIBUTES = [
  "strength",
  "agility",
  "intelligence"
];

export const ATTACK_TYPES = [
  "MELEE",
  "RANGED"
];